# Generated by Django 5.0.4 on 2024-04-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adress",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
