# Generated by Django 5.0.4 on 2024-04-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0004_alter_adress_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adress",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Configuration_line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "configuration_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configurations.configuration",
                    ),
                ),
            ],
        ),
    ]
