# Generated by Django 5.0.4 on 2024-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configurations",
            "0012_rename_address_id_configuration_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(model_name="address", name="postal_code", field=models.CharField(max_length=100)),
    ]
