# Generated by Django 5.0.4 on 2024-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_question"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product_question",
            table="ratings",
        ),
    ]
