# Generated by Django 5.0.4 on 2024-04-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('configurations', '0008_rename_configuration_line_configurationline'),
        ('products', '0006_product_question_article'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Question',
            new_name='ProductQuestion',
        ),
        migrations.RenameModel(
            old_name='Product_question_article',
            new_name='ProductQuestionArticle',
        ),
    ]
